/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lee_asher_ndkstudy_JniTest */

#ifndef _Included_com_lee_asher_ndkstudy_JniTest
#define _Included_com_lee_asher_ndkstudy_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lee_asher_ndkstudy_JniTest
 * Method:    getPackname
 * Signature: (Ljava/lang/Object;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_lee_asher_ndkstudy_JniTest_getPackname
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
